name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: a2_tests
      id: a2_tests
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 10
        setup-command: pip3 install pytest torch numpy
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        A2_TESTS_RESULTS: "${{steps.a2_tests.outputs.result}}"
      with:
        runners: a2_tests
